[profile.default]
src = "src"
out = "out"
scripts = "script"
libs = ["lib"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", "@era/contracts=lib/foundry-era-contracts/src/system-contracts/contracts"]
via-ir = true
optimizer = true
optimizer_runs = 200

[profile.zksync]
src = "src"
libs = ["lib"]
fallback_oz = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
